DROP DATABASE IF EXISTS employeeTracker_db;
CREATE DATABASE employeeTracker_db;
USE employeeTracker_db;

CREATE TABLE department (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(30) NOT NULL
);
CREATE TABLE role (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL UNSIGNED NOT NULL,
  departmentID INT UNSIGNED NOT NULL,
  FOREIGN KEY (departmentID) REFERENCES department(id) ON DELETE CASCADE
);
CREATE TABLE employee (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(30) NOT NULL,
  last_name VARCHAR(30) NOT NULL,
  roleID INT UNSIGNED NOT NULL,
  FOREIGN KEY (roleID) REFERENCES role(id) ON DELETE CASCADE,
  managerID INT UNSIGNED,
  FOREIGN KEY (managerID) REFERENCES employee(id) ON DELETE SET NULL
);





